[project]
name = "simple_auto_cover"
version = "2.0.0"
description = "Simple Auto Cover"
authors = [{ name = "Travis Pew" }]
requires-python = ">=3.13.2,<3.14"
readme = "README.md"
license = "MIT"
maintainers = [{ name = "Travis Pew" }]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "homeassistant==2026.2.3",
    "numpy",
    "python-dateutil",
]

[project.urls]
Homepage = "https://github.com/travisp/adaptive-cover"
Repository = "https://github.com/travisp/adaptive-cover"
Documentation = "https://github.com/travisp/adaptive-cover"
"Bug Tracker" = "https://github.com/travisp/adaptive-cover/issues"
Changelog = "https://github.com/travisp/adaptive-cover/releases"

[dependency-groups]
dev = [
    "colorlog~=6.12",
    "ipykernel~=7.3",
    "matplotlib~=3.11",
    "pre-commit==4.6.1",
    "pvlib~=0.15.2",
    "pylint==4.0.6",
    "pytest==9.0.0",
    "pytest-homeassistant-custom-component==0.13.316",
    "ruff==0.16.0",
]

[tool.hatch.build.targets.sdist]
include = ["custom_components/simple_auto_cover"]

[tool.hatch.build.targets.wheel]
include = ["custom_components/simple_auto_cover"]

[tool.hatch.build.targets.wheel.sources]
"custom_components/simple_auto_cover" = "simple_auto_cover"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"

[tool.pylint."MESSAGES CONTROL"]
# Reasons disabled:
# format - handled by ruff
# duplicate-code - unavoidable
# used-before-assignment - false positives with TYPE_CHECKING structures
disable = [
  "format",
  "duplicate-code",
  "used-before-assignment",
]
